name: Build and Push Docker Image

on:
  push:
    branches:
      - main


jobs:
  create-version-number:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}.${{ github.run_number }}
    steps:
      - id: version
        run: echo "version=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: create-version-number

    steps:
      - uses: actions/checkout@v3

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -f src/WebApp/Dockerfile -t ghcr.io/adamoctoclose/pitstop-personal-webapp:${{ needs.create-version-number.outputs.version }} src/WebApp
          docker push ghcr.io/adamoctoclose/pitstop-personal-webapp:${{ needs.create-version-number.outputs.version }}
